src/Entity/Film.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FilmRepository")
 */
class Film
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $affiche;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $duree;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_sortie;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Realisateur", inversedBy="films")
     * @ORM\JoinColumn(nullable=false)
     */
    private $realisateur;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Acteur", inversedBy="films")
     */
    private $acteur;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Categorie", inversedBy="films")
     */
    private $categorie;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\BandeAnnonce", mappedBy="film")
     */
    private $bande_annonce;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Photo", mappedBy="film")
     */
    private $photo;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Salle", inversedBy="films")
     */
    private $salle;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commentaire", mappedBy="film")
     */
    private $commentaire;

    /**
     * @ORM\Column(type="integer")
     */
    private $etat;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Sceance", mappedBy="film")
     */
    private $sceance;

    public function __construct()
    {
        $this->acteur = new ArrayCollection();
        $this->categorie = new ArrayCollection();
        $this->bande_annonce = new ArrayCollection();
        $this->photo = new ArrayCollection();
        $this->salle = new ArrayCollection();
        $this->commentaire = new ArrayCollection();
        $this->sceance = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getAffiche(): ?string
    {
        return $this->affiche;
    }

    public function setAffiche(string $affiche): self
    {
        $this->affiche = $affiche;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDuree(): ?string
    {
        return $this->duree;
    }

    public function setDuree(string $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getDateSortie(): ?\DateTimeInterface
    {
        return $this->date_sortie;
    }

    public function setDateSortie(\DateTimeInterface $date_sortie): self
    {
        $this->date_sortie = $date_sortie;

        return $this;
    }

    public function getRealisateur(): ?Realisateur
    {
        return $this->realisateur;
    }

    public function setRealisateur(?Realisateur $realisateur): self
    {
        $this->realisateur = $realisateur;

        return $this;
    }

    /**
     * @return Collection|Acteur[]
     */
    public function getActeur(): Collection
    {
        return $this->acteur;
    }

    public function addActeur(Acteur $acteur): self
    {
        if (!$this->acteur->contains($acteur)) {
            $this->acteur[] = $acteur;
        }

        return $this;
    }

    public function removeActeur(Acteur $acteur): self
    {
        if ($this->acteur->contains($acteur)) {
            $this->acteur->removeElement($acteur);
        }

        return $this;
    }

    /**
     * @return Collection|Categorie[]
     */
    public function getCategorie(): Collection
    {
        return $this->categorie;
    }

    public function addCategorie(Categorie $categorie): self
    {
        if (!$this->categorie->contains($categorie)) {
            $this->categorie[] = $categorie;
        }

        return $this;
    }

    public function removeCategorie(Categorie $categorie): self
    {
        if ($this->categorie->contains($categorie)) {
            $this->categorie->removeElement($categorie);
        }

        return $this;
    }

    /**
     * @return Collection|BandeAnnonce[]
     */
    public function getBandeAnnonce(): Collection
    {
        return $this->bande_annonce;
    }

    public function addBandeAnnonce(BandeAnnonce $bandeAnnonce): self
    {
        if (!$this->bande_annonce->contains($bandeAnnonce)) {
            $this->bande_annonce[] = $bandeAnnonce;
            $bandeAnnonce->setFilm($this);
        }

        return $this;
    }

    public function removeBandeAnnonce(BandeAnnonce $bandeAnnonce): self
    {
        if ($this->bande_annonce->contains($bandeAnnonce)) {
            $this->bande_annonce->removeElement($bandeAnnonce);
            // set the owning side to null (unless already changed)
            if ($bandeAnnonce->getFilm() === $this) {
                $bandeAnnonce->setFilm(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Photo[]
     */
    public function getPhoto(): Collection
    {
        return $this->photo;
    }

    public function addPhoto(Photo $photo): self
    {
        if (!$this->photo->contains($photo)) {
            $this->photo[] = $photo;
            $photo->setFilm($this);
        }

        return $this;
    }

    public function removePhoto(Photo $photo): self
    {
        if ($this->photo->contains($photo)) {
            $this->photo->removeElement($photo);
            // set the owning side to null (unless already changed)
            if ($photo->getFilm() === $this) {
                $photo->setFilm(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Salle[]
     */
    public function getSalle(): Collection
    {
        return $this->salle;
    }

    public function addSalle(Salle $salle): self
    {
        if (!$this->salle->contains($salle)) {
            $this->salle[] = $salle;
        }

        return $this;
    }

    public function removeSalle(Salle $salle): self
    {
        if ($this->salle->contains($salle)) {
            $this->salle->removeElement($salle);
        }

        return $this;
    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaire(): Collection
    {
        return $this->commentaire;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaire->contains($commentaire)) {
            $this->commentaire[] = $commentaire;
            $commentaire->setFilm($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaire->contains($commentaire)) {
            $this->commentaire->removeElement($commentaire);
            // set the owning side to null (unless already changed)
            if ($commentaire->getFilm() === $this) {
                $commentaire->setFilm(null);
            }
        }

        return $this;
    }

    public function getEtat(): ?int
    {
        return $this->etat;
    }

    public function setEtat(int $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    /**
     * @return Collection|Sceance[]
     */
    public function getSceance(): Collection
    {
        return $this->sceance;
    }

    public function addSceance(Sceance $sceance): self
    {
        if (!$this->sceance->contains($sceance)) {
            $this->sceance[] = $sceance;
            $sceance->setFilm($this);
        }

        return $this;
    }

    public function removeSceance(Sceance $sceance): self
    {
        if ($this->sceance->contains($sceance)) {
            $this->sceance->removeElement($sceance);
            // set the owning side to null (unless already changed)
            if ($sceance->getFilm() === $this) {
                $sceance->setFilm(null);
            }
        }

        return $this;
    }
}

src/Controller/CineController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\RegistrationType;

use App\Repository\FilmRepository;
use App\Repository\SalleRepository;
use App\Repository\ActeurRepository;
use App\Repository\SceanceRepository;
use App\Repository\CategorieRepository;
use App\Repository\RealisateurRepository;
use App\Entity\Sceance;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CineController extends AbstractController
{
    /**
     * @Route("/inscription", name="security_registration", methods={"GET","POST"})
     */
    public function registration(Request $request, ObjectManager $mana)
    {
        $user = new User();
        $form = $this->createForm(RegistrationType::class, $user);
        
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $mana->persist($user);
            $mana->flush();
            $this->addFlash('success', 'User Created! Knowledge is power!');
            return $this->redirectToRoute('cine');
        }

        return $this->render('security/index.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/acteur/{id}", name="acteur_show", methods={"GET"})
     */
    public function acteurShow(ActeurRepository $racteur, string $id)
    {
        $acteur = $racteur->find($id);

        return $this->render('cine/acteurshow.html.twig', [
            'controller_name' => 'CineController',
            'acteur' => $acteur
        ]);
    }

    /**
     * @Route("/categorie/{id}", name="categorie_show", methods={"GET"})
     */
    public function categorieShow(CategorieRepository $rcategorie, string $id)
    {
        $categorie = $rcategorie->find($id);

        return $this->render('cine/categorieshow.html.twig', [
            'controller_name' => 'CineController',
            'categorie' => $categorie
        ]);
    }
    
    /**
     * @Route("/realisateur/{id}", name="realisateur_show", methods={"GET"})
     */
    public function realisateurShow(RealisateurRepository $rrealisateur, string $id)
    {
        $realisateur = $rrealisateur->find($id);

        return $this->render('cine/realisateurshow.html.twig', [
            'controller_name' => 'CineController',
            'realisateur' => $realisateur
        ]);
    }
    
    /**
     * @Route("/cine/{id}", name="cine_show", methods={"GET"})
     */
    public function cineShow(FilmRepository $rfilm, string $id)
    {
        $film = $rfilm->find($id);
        //calcul de la moyenne du film 
        $moyenne=0;
        $sommeNote=0;
        $nbNote=0;
        foreach ($film->getCommentaire() as $commentaire) {
            $sommeNote+=$commentaire->getNote();
            $nbNote++;
        }
        if ($nbNote!=0) {
            $moyenne=$sommeNote/$nbNote;
        }

        return $this->render('cine/filmshow.html.twig', [
            'controller_name' => 'CineController',
            'film' => $film,
                        'note'=>$moyenne
        ]);
    }

    /**
     * @Route("/salle/{id}", name="salle_show", methods={"GET"})
     */
    public function salleShow(SalleRepository $rsalle, string $id )
    {
        $salle = $rsalle->find($id);

        return $this->render('cine/salleshow.html.twig', [
            'controller_name' => 'CineController',
            'salle' => $salle
        ]);
    }

    /**
     * @Route("/seance/{id}", name="seance_show", methods={"GET"})
     */
    public function seanceShow(Sceance $rseance)
    {
  
        return $this->render('cine/seanceshow.html.twig', [
            'controller_name' => 'CineController',
            'seance' => $rseance
        ]);
    }

     /**
     * @Route("/seance", name="seance", methods={"GET"})
     */
    public function seance(SceanceRepository $rseance)
    {
        $seance = $rseance->findAll();

        return $this->render('cine/seance.html.twig', [
            'controller_name' => 'CineController',
            'seance' => $seance
        ]);
    }


     /**
     * @Route("/salles", name="salles", methods={"GET"})
     */
    public function salles(SalleRepository $rsalles)
    {
        $salles = $rsalles->findAll();

        return $this->render('cine/salles.html.twig', [
            'controller_name' => 'CineController',
            'salles' => $salles
        ]);
    }

    /**
     * @Route("/categorie", name="categorie", methods={"GET"})
     */
    public function categorie(CategorieRepository $rcategorie)
    {
        $categorie = $rcategorie->findAll();

        return $this->render('cine/categorie.html.twig', [
            'controller_name' => 'CineController',
            'categorie' => $categorie
        ]);
    }

    /**
     * @Route("/realisateur", name="realisateur", methods={"GET"})
     */
    public function realisateur(RealisateurRepository $rrealisateur)
    {
        $realisateur = $rrealisateur->findAll();
        
        return $this->render('cine/realisateur.html.twig', [
            'controller_name' => 'CineController',
            'realisateur' => $realisateur
        ]);
    }

    /**
     * @Route("/acteur", name="acteur", methods={"GET"})
     */
    public function acteur(ActeurRepository $racteur)
    {
        $acteur = $racteur->findAll();
        
        return $this->render('cine/acteur.html.twig', [
            'controller_name' => 'CineController',
            'acteur' => $acteur
        ]);
    }

    /**
     * @Route("/", name="home")
     * @Route("/cine", name="cine")
     */
    public function cine(FilmRepository $rfilm)
    {
        $films = $rfilm->findAll();
        //les films a l'affiche
        $affiche=[];
        foreach ($films as $film) {
            if ($film->getEtat() == 1) {
                $affiche[]=$film;
            }
        }
        
        return $this->render('cine/index.html.twig', [
            'controller_name' => 'CineController',
            'Aaffiche' => $affiche,

        ]);
    }
}

templates/cine/acteur.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CineController!{% endblock %}

{% block body %}
<div class="container-lg">
    <div class="row row-cols-1 row-cols-md-3">
        {% for act in acteur %}  
      <div class="col mb-4">
          <div class="card h-100" >
            <img src="{{act.photo}}" class="card-img-top" alt="photo de l'acteur {{act.nom}} {{act.prenom}}">
            <div class="card-body">
              <h5 class="card-title">{{act.nom}} {{act.prenom}}</h5>
              <p class="card-text"><small class="text-muted">Cet acteur a jouer dans {{act.films|length}} films </small></p>
              <a href="{{path('acteur_show', {'id': act.id})}}" type="button" class="btn btn-outline-info">Voir l'acteur</a>
            </div>
          </div>
        </div>
        {% endfor %}
    </div>
    
</div>

{% endblock %}

templates/cine/acteurshow.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CineController!{% endblock %}

{% block body %}
<div class="container-lg">
	<div class="card mb-3">
      <div class="row no-gutters">
        <div class="col-md-4">
          <img src="{{acteur.photo}}" class="card-img" alt="photo de l'acteur {{acteur.nom}} {{acteur.prenom}}">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">{{acteur.nom}} {{acteur.prenom}}</h5>
            <p class="card-text"><small class="text-muted">Cet acteur a jouer dans {{acteur.films|length}} films </small></p>
          </div>
        </div>
      </div>
    </div>
    <br>
    <div class="row row-cols-1 row-cols-md-3">
   {% for film in acteur.films %} 
  <div class="col mb-4">
    <div class="card">
      <img src="{{film.affiche}}" class="card-img-top" alt="image du film {{film.titre}}">
      <div class="card-body">
        <h5 class="card-title">{{film.titre}}</h5>
        <p class="card-text">{{film.description|slice(0,150)}}</p>
        <a href="{{path('cine_show', {'id': film.id})}}"type="button" class="btn btn-outline-info">Voir le film</a>
      </div>
    </div>
   
  </div>
   {% endfor %}
</div>
</div>
    


{% endblock %}

templates/cine/categorieshow.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CineController!{% endblock %}

{% block body %}

<div class="container-lg">
  <div class="row row-cols-1 row-cols-md-3">
    {% for film in categorie.films %} 
    <div class="col mb-4">
        
      <div class="card " >
        <img src="{{film.affiche}}" class="card-img-top" alt="image du film {{film.titre}}">
        <div class="card-body">
          <h5 class="card-title">{{film.titre}}</h5>
          <p>{{film.duree}} - {{ film.dateSortie|date("Y-m-d")}} </p>
            <p>{{film.description|slice(0,150) }} </p> 
          <p class="card-text"><small class="text-muted">Ce film est diffusé dans {{film.salle|length}} salle(s) </small></p>
          <a href="{{path('cine_show', {'id': film.id})}}"type="button" class="btn btn-outline-info">Voir plus</a>
        </div>
      </div>
      
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

templates/cine/filmshow.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CineController!{% endblock %}

{% block body %}

<br>
<div class="container-lg">
    <div class="card mb-3">
      <div class="row no-gutters">
        <div class="col-md-4">
          <img src="{{film.affiche}}" class="card-img" alt="image de {{film.titre}}">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">{{film.titre}}</h5>
            {% if note>0  %}
            {% for i in 1..note %}
            <svg class="bi bi-star-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
            </svg>
            {% endfor %}
            {% endif %}
            {% if note < 10 %}
            {% for i in note+1..10 %}
            <svg class="bi bi-star" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.523-3.356c.329-.314.158-.888-.283-.95l-4.898-.696L8.465.792a.513.513 0 00-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767l-3.686 1.894.694-3.957a.565.565 0 00-.163-.505L1.71 6.745l4.052-.576a.525.525 0 00.393-.288l1.847-3.658 1.846 3.658a.525.525 0 00.393.288l4.052.575-2.906 2.77a.564.564 0 00-.163.506l.694 3.957-3.686-1.894a.503.503 0 00-.461 0z" clip-rule="evenodd"/>
            </svg>

            {% endfor %}
            {% endif %}
            {{film.commentaire|length}} avis
            <h5 class="text-danger">sortie: {{film.dateSortie|date("Y/m/d")}}</h5>
            <p>duree: {{film.duree}}</p>

            <p class="card-text">{{film.description}}</p>
            
            <h5 class="text-primary">
            {% for cat in film.categorie %}
                {{cat.titre}} 
                {% endfor %} 
            </h5>
            <h5 class="text-success"><a href="{{path('realisateur_show',{id:film.realisateur.id})}}">{{film.realisateur.nom}} {{film.realisateur.prenom}}</a></h5>
          </div>
        </div>
      </div>
    </div>

    {% if film.photo is not empty %}
    <div id="carouselExampleControls" class="carousel slide mx-auto" data-ride="carousel" style="max-width: 800px;">
      <div class="carousel-inner">
        <div class="carousel-item active w-100 mx-auto">
          <img src="{{film.photo[0].lien}}" class="d-block w-100" alt="image de {{film.titre}}">
        </div>
        {% for photo in film.photo %}
        {% if not loop.first%}
        <div class="carousel-item">
          <img src="{{photo.lien}}" class="d-block w-100" alt="photo de {{film.titre}}">
        </div>
        {% endif %}
        {% endfor %}
        {% for ba in film.bandeAnnonce %}
        <div class="carousel-item">
            <iframe width="725" height="408" src="https://www.youtube.com/embed/{{ba.lien}}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
        {% endfor %}
      </div>
      <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
    {% endif %}
    <br>
    {% if film.acteur is not empty %}
    <h3 class="text-muted text-center">Acteurs du film</h3>
    <div class="row">
        {% for acteur in film.acteur %}
        <div class="card col" style="max-width: 300px;">
            <div class="row no-gutters">
                <div class="col-md-4">
                    <img src="{{acteur.photo}}" class="card-img" alt="photo de l'acteur {{acteur.nom}} {{acteur.prenom}}">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">{{acteur.nom}} {{acteur.prenom}}</h5>
                        <p class="card-text">cet acteur a jouer dans {{acteur.films|length}} film(s)</p>
                    </div>
                    <a href="{{path('acteur_show',{'id':acteur.id})}}" class="btn btn-outline-primary">Voir l'acteur</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endif %}
    <br>
    {%if film.commentaire is not empty%}
    <div class= "card">
        <h3 class="text-muted text-center">Commentaires</h3>
        {% for commentaire in film.commentaire %}
        <div class="card border-warning mb-3">
            <div class="card-header">{{commentaire.pseudo}}</div>
            <div class="card-body">
                <h5 class="card-title">{{commentaire.date|date("m/d/Y")}}</h5>
                {% set note= commentaire.note%}
                {% if note>0%}
            {% for i in 1..note %}
            <svg class="bi bi-star-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
            </svg>
            {% endfor %}
            {% endif %}
            {% if note<10 %}
            {% for i in note+1..10 %}
            <svg class="bi bi-star" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.523-3.356c.329-.314.158-.888-.283-.95l-4.898-.696L8.465.792a.513.513 0 00-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767l-3.686 1.894.694-3.957a.565.565 0 00-.163-.505L1.71 6.745l4.052-.576a.525.525 0 00.393-.288l1.847-3.658 1.846 3.658a.525.525 0 00.393.288l4.052.575-2.906 2.77a.564.564 0 00-.163.506l.694 3.957-3.686-1.894a.503.503 0 00-.461 0z" clip-rule="evenodd"/>
            </svg>
            {% endfor %}
            {% endif %}
                <p class="card-text">{{commentaire.commentaire}}</p>
             </div>
        </div>
        {% endfor %}
    </div>
    {% endif %}

</div>

    
{% endblock %}

templates/cine/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CineController!{% endblock %}

{% block body %}

<div class="container-lg">    
  <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel" style="margin: auto">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
      {% for film in Aaffiche %}
      <li data-target="#carouselExampleCaptions" data-slide-to="{{loop.index}}"></li>
      {% endfor %}
    </ol>
    {% set premier=Aaffiche|first %}
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{{(premier.photo|first).lien}}" alt="image du film {{premier.titre}}" class="d-block w-100" >
        <div class="carousel-caption d-none d-md-block">
          <h5>{{premier.titre}}</h5>
          <p>{{premier.duree}}</p>
          <p>{{premier.dateSortie|date("Y-m-d")}}</p>
        </div>
      </div>
      {% for film in Aaffiche|slice(1)%}
      {% if film.photo is not empty%}
      <div class="carousel-item">
        <img src="{{(film.photo|first).lien}}" alt="image du film {{film.titre}}">
        <div class="carousel-caption d-none d-md-block">
          <h5>{{film.titre}}</h5>
          <p>{{film.duree}}</p>
          <p>{{film.dateSortie|date("Y-m-d")}}</p>
        </div>
      </div>
      {% endif %}
      {% endfor %}
    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <br>
  <h2>Les films a l'affiche</h2>
  <div class="row row-cols-1 row-cols-md-3">
    {% for film in Aaffiche %} 
    <div class="col mb-4">
        
      <div class="card " >
        <img src="{{film.affiche}}" class="card-img-top" alt="image du film {{film.titre}}">
        <div class="card-body">
          <h5 class="card-title">{{film.titre}}</h5>
          <p>{{film.duree}} - {{ film.dateSortie|date("Y-m-d")}} </p>
            <p>{{film.description|slice(0,150) }} </p> 
          <p class="card-text"><small class="text-muted">Ce film est diffusé dans {{film.salle|length}} salle(s) </small></p>
          <a href="{{path('cine_show', {'id': film.id})}}"type="button" class="btn btn-outline-info">Voir plus</a>
        </div>
      </div>
      
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

templates/cine/realisateur.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CineController!{% endblock %}

{% block body %}

<div class="container-lg">
<div class="row row-cols-1 row-cols-md-3">
   {% for real in realisateur %} 
  <div class="col mb-4">
     
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{real.prenom}} {{real.nom}}</h5>
        <p class="card-text"><small class="text-muted">{{real.films|length}} films realisés</small></p>
        <a href="{{path('realisateur_show', {'id': real.id})}}" type="button" class="btn btn-outline-info">Voir plus</a>
      </div>
    </div>
   
  </div>
   {% endfor %}
</div>
</div>

{% endblock %}